
---
version: '3.7'
services:
  mattermost :
    image: mattermost/mattermost-preview
    container_name: mattermostserver
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.routers.mattermost.rule=Host(`matter-server.ddns.net`)"
      - "traefik.http.routers.mattermost.tls=true"
      - "traefik.http.routers.mattermost.tls.certresolver=default"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
    networks:
      - traefik_proxy

traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
      - ./acme/:/acme/
    environment:
      - TZ=Europe/Berlin
    restart: always
    command: --api
    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

