name: Build and deploy

on:
  push:
    branches:
      - main
      
  
  
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout 
        uses: actions/checkout@v2
                  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Setting DB Connection String
        run: touch src/.env && echo "${{ secrets.DB_HOST }}" >> src/.env && echo "${{ secrets.DB_PASSWORD }}" >> src/.env && echo "${{ secrets.SESSION_PWD }}" >> src/.env
        
        
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          file: ./server/Dockerfile
          tags: mattermost-preview-image
          
      - name: Delete old docker images (locally)
        run: docker rmi -f mattermost-preview-image
         
      - name: Delete old docker Instances
        run: docker rm -f mattermost-preview
        
      - name: Start Docker-App
        run: docker run --name mattermost-preview -d --publish 80:8065 --add-host dockerhost:127.0.0.1 mattermost-preview-image

        